config/routes.rb
Rails.application.routes.draw do
  resources :costs
  root 'costs#index'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  validates :title, presence:{ message:"please write title!!"}
  validates_numericality_of :money, pressence:{ message:'please write price!'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
    
    @num = ['01','02','03','04','05','06','07','08','09','10','11','12']
    @month = []
    @total = []
    (0..11).each do |i|
      @month[i] = Cost.where(["date_part('year', cost_date) = ? and date_part('month', cost_date) = ?", 2015, @num[i]]).order('cost_date')
      @total[i] = Cost.where(["date_part('year', cost_date) = ? and date_part('month', cost_date) = ?", 2015, @num[i]]).sum(:money)
    end
    Cost.where(["date_part('month',buyday) = ?", 3])
    
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:cost_date, :title, :money)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost_date %><br>
    <%= f.date_select :cost_date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.number_field :money %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<div role="tabpanel">  
  <ul class="nav nav-tabs" role="tablist">
    <% (0..11).each do |i| %>
    <li role="presentation"><a href="#<%= @num[i] %>" role="tab" data-toggle="tab"><%= @num[i] %>月</a></li>
    <% end %>
  </ul>
  
  <div class="tab-content">
    <% (0..11).each do |i| %>
      <div role="tabpanel" class="tab-pane" id="<%= @num[i] %>">
        <h1>帳目表</h1>
        <h3><%= i+1 %>月</h3>
        <table class="table">
          <thead>
            <tr>
              <th>日期</th>
              <th>項目</th>
              <th>金額</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @month[i].each do |cost| %>
              <tr>
                <td><%= cost.cost_date %></td>
                <td><%= cost.title %></td>
                <td><%= cost.money %></td>
                <td><%= link_to 'Show', cost %></td>
                <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
                <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
          <tr>
            <td></td>
            <td>總計</td>
            <td><%= @total[i] %></td>
            <td></td>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to '新增', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost date:</strong>
  <%= @cost.cost_date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @cost.title %>
</p>

<p>
  <strong>Money:</strong>
  <%= @cost.money %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muchmoney</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>